"""A lightweight paper-trading engine with a simple order-state machine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Sequence

from src.backtest.costs import CostModel, build_default_cost_model
from src.risk.controls import CircuitBreaker, RiskManager
from src.risk.kill_switch import KillSwitchController
from src.storage.trade_logger import TradeLogger


@dataclass(slots=True)
class PaperOrder:
    """Simple order model for paper-trading execution."""

    id: str
    timestamp: datetime
    side: str
    size: float
    status: str = "PENDING_SUBMIT"
    filled_size: float = 0.0
    avg_fill_price: float = 0.0
    fees: float = 0.0
    age_bars: int = 0
    created_at: datetime | None = None
    last_updated_at: datetime | None = None

    def __post_init__(self) -> None:
        self.created_at = self.timestamp
        self.last_updated_at = self.timestamp

    @property
    def remaining_size(self) -> float:
        """Return the remaining order size."""
        return self.size - self.filled_size


@dataclass(slots=True)
class PaperTrade:
    """A simulated fill generated by the paper-trading engine."""

    order_id: str
    timestamp: datetime
    side: str
    price: float
    size: float
    fee: float
    cost: float


@dataclass(slots=True)
class PortfolioSnapshot:
    """Portfolio snapshot after each processing step."""

    timestamp: datetime
    cash: float
    position_size: float
    avg_entry_price: float | None
    equity: float


@dataclass(slots=True)
class PaperTradingResult:
    """Result bundle from a paper-trading run."""

    orders: list[PaperOrder] = field(default_factory=list)
    trades: list[PaperTrade] = field(default_factory=list)
    equity_curve: list[float] = field(default_factory=list)
    portfolio_history: list[PortfolioSnapshot] = field(default_factory=list)
    entry_decisions: list[dict[str, Any]] = field(default_factory=list)


class PaperTradingEngine:
    """Run a simple signal-driven paper-trading loop over OHLC-like bars."""

    def __init__(
        self,
        *,
        initial_cash: float = 100.0,
        default_order_size: float = 1.0,
        partial_fill_fraction: float = 1.0,
        max_order_lifetime_bars: int = 2,
        cost_model: CostModel | None = None,
        risk_manager: RiskManager | None = None,
        trade_logger: TradeLogger | None = None,
        execution_adapter: Any | None = None,
        circuit_breaker: CircuitBreaker | None = None,
        kill_switch_controller: KillSwitchController | None = None,
        exchange_name: str | None = None,
    ) -> None:
        """Initialize the object with its runtime state."""
        if initial_cash <= 0:
            raise ValueError("initial_cash must be positive")
        if default_order_size <= 0:
            raise ValueError("default_order_size must be positive")
        if not 0.0 < partial_fill_fraction <= 1.0:
            raise ValueError("partial_fill_fraction must be between 0 and 1")
        if max_order_lifetime_bars < 1:
            raise ValueError("max_order_lifetime_bars must be at least 1")

        self.initial_cash = initial_cash
        self.default_order_size = default_order_size
        self.partial_fill_fraction = partial_fill_fraction
        self.max_order_lifetime_bars = max_order_lifetime_bars
        self.cost_model = cost_model or build_default_cost_model("mock")
        self.risk_manager = risk_manager
        self.trade_logger = trade_logger
        self.execution_adapter = execution_adapter
        self.circuit_breaker = circuit_breaker
        self.kill_switch_controller = kill_switch_controller
        self.exchange_name = exchange_name or getattr(execution_adapter, "exchange_name", None) or getattr(execution_adapter, "name", None) or "paper"
        self._order_counter = 0

    def run(self, bars: Sequence[Any], signals: Sequence[float | int | str | None]) -> PaperTradingResult:
        """Process a stream of bars and signals into simulated orders and fills."""
        if len(bars) != len(signals):
            raise ValueError("bars and signals must be the same length")
        if not bars:
            return PaperTradingResult()

        cash = self.initial_cash
        position_size = 0.0
        avg_entry_price: float | None = None
        peak_equity = self.initial_cash
        orders: list[PaperOrder] = []
        trades: list[PaperTrade] = []
        equity_curve: list[float] = []
        portfolio_history: list[PortfolioSnapshot] = []
        entry_decisions: list[dict[str, Any]] = []
        active_orders: list[PaperOrder] = []

        for index, bar in enumerate(bars):
            signal = _normalize_signal(signals[index])
            price = _get_close(bar)
            timestamp = _get_timestamp(bar)

            if not active_orders and signal > 0 and position_size <= 0.0:
                risk_decision = self._evaluate_risk(
                    bars=list(bars[: index + 1]),
                    equity=cash + (position_size * price if position_size else 0.0),
                    peak_equity=peak_equity,
                    current_position=position_size,
                    current_bar=bar,
                    bar_index=index,
                    signal_side="buy",
                    current_notional=max(0.0, position_size * price),
                    open_positions=1 if position_size != 0.0 else 0,
                    exchange_name=self.exchange_name,
                    exchange_position_size=position_size,
                    current_exchange_notional=max(0.0, position_size * price),
                    exchange_open_positions=1 if position_size != 0.0 else 0,
                    open_orders_count=len(active_orders),
                )
                self._record_entry_decision(
                    decisions=entry_decisions,
                    signal=signal,
                    side="buy",
                    allowed=risk_decision.allow_entry,
                    reason=getattr(risk_decision, "reason", None),
                    price=price,
                    timestamp=timestamp,
                    order_size=risk_decision.position_size,
                )
                if not risk_decision.allow_entry:
                    pass
                else:
                    order_size = max(0.0, min(self.default_order_size, risk_decision.position_size))
                    if order_size > 0.0:
                        order = self._create_order(timestamp=timestamp, side="buy", size=order_size)
                        active_orders.append(order)
                        orders.append(order)
                        cash, position_size, avg_entry_price = self._maybe_route_order(
                            order=order,
                            price=price,
                            timestamp=timestamp,
                            cash=cash,
                            position_size=position_size,
                            avg_entry_price=avg_entry_price,
                            trades=trades,
                        )
                        if order.status in {"FILLED", "CANCELED"}:
                            active_orders.remove(order)
            elif not active_orders and signal < 0 and position_size >= 0.0:
                risk_decision = self._evaluate_risk(
                    bars=list(bars[: index + 1]),
                    equity=cash + (position_size * price if position_size else 0.0),
                    peak_equity=peak_equity,
                    current_position=position_size,
                    current_bar=bar,
                    bar_index=index,
                    signal_side="sell",
                    current_notional=max(0.0, position_size * price),
                    open_positions=1 if position_size != 0.0 else 0,
                    exchange_name=self.exchange_name,
                    exchange_position_size=position_size,
                    current_exchange_notional=max(0.0, position_size * price),
                    exchange_open_positions=1 if position_size != 0.0 else 0,
                    open_orders_count=len(active_orders),
                )
                self._record_entry_decision(
                    decisions=entry_decisions,
                    signal=signal,
                    side="sell",
                    allowed=risk_decision.allow_entry,
                    reason=getattr(risk_decision, "reason", None),
                    price=price,
                    timestamp=timestamp,
                    order_size=risk_decision.position_size,
                )
                if not risk_decision.allow_entry:
                    pass
                else:
                    order_size = max(0.0, min(self.default_order_size, risk_decision.position_size))
                    if order_size > 0.0:
                        order = self._create_order(timestamp=timestamp, side="sell", size=order_size)
                        active_orders.append(order)
                        orders.append(order)
                        cash, position_size, avg_entry_price = self._maybe_route_order(
                            order=order,
                            price=price,
                            timestamp=timestamp,
                            cash=cash,
                            position_size=position_size,
                            avg_entry_price=avg_entry_price,
                            trades=trades,
                        )
                        if order.status in {"FILLED", "CANCELED"}:
                            active_orders.remove(order)

            for order in list(active_orders):
                if order.status == "PENDING_SUBMIT":
                    order.status = "OPEN"
                    order.last_updated_at = timestamp
                    continue

                if order.status == "OPEN" and order.remaining_size > 0.0:
                    order.age_bars += 1
                    if order.age_bars >= self.max_order_lifetime_bars:
                        order.status = "CANCELED"
                        order.last_updated_at = timestamp
                        active_orders.remove(order)
                        continue

                    fill_size = min(order.remaining_size, self.default_order_size * self.partial_fill_fraction)
                    if fill_size <= 0.0:
                        continue

                    gross_price = price
                    execution_price = self._apply_cost(price, side=order.side, size=fill_size)
                    cost = abs(execution_price - gross_price) * fill_size
                    if order.side == "buy" and cash >= execution_price * fill_size:
                        cash -= execution_price * fill_size
                        position_size += fill_size
                        avg_entry_price = self._update_average_price(
                            current_position=position_size,
                            average_price=avg_entry_price,
                            fill_size=fill_size,
                            fill_price=execution_price,
                        )
                    elif order.side == "sell" and position_size >= fill_size:
                        cash += execution_price * fill_size
                        position_size -= fill_size
                        if position_size <= 0.0:
                            avg_entry_price = None
                        else:
                            avg_entry_price = avg_entry_price
                    else:
                        order.status = "CANCELED"
                        order.last_updated_at = timestamp
                        active_orders.remove(order)
                        continue

                    order.filled_size += fill_size
                    order.avg_fill_price = execution_price
                    order.fees += cost
                    order.last_updated_at = timestamp
                    if order.remaining_size <= 0.0:
                        order.status = "FILLED"
                        active_orders.remove(order)
                    else:
                        order.status = "PARTIALLY_FILLED"

                    trades.append(
                        PaperTrade(
                            order_id=order.id,
                            timestamp=timestamp,
                            side=order.side,
                            price=execution_price,
                            size=fill_size,
                            fee=cost,
                            cost=cost,
                        )
                    )
                    if self.trade_logger is not None:
                        self.trade_logger.log_trade(
                            timestamp=timestamp,
                            source="paper_trading",
                            exchange="mock",
                            pair="BTC/NOK",
                            side=order.side,
                            price=execution_price,
                            size=fill_size,
                            fee=cost,
                            role_maker_taker="taker",
                            latency_ms=0,
                        )

            equity = cash + (position_size * price if position_size else 0.0)
            peak_equity = max(peak_equity, equity)
            equity_curve.append(equity)
            portfolio_history.append(
                PortfolioSnapshot(
                    timestamp=timestamp,
                    cash=cash,
                    position_size=position_size,
                    avg_entry_price=avg_entry_price,
                    equity=equity,
                )
            )
            if self.trade_logger is not None:
                self.trade_logger.log_equity_snapshot(
                    timestamp=timestamp,
                    source="paper_trading",
                    equity=equity,
                    cash=cash,
                    position_size=position_size,
                )

        return PaperTradingResult(
            orders=orders,
            trades=trades,
            equity_curve=equity_curve,
            portfolio_history=portfolio_history,
            entry_decisions=entry_decisions,
        )

    def _record_entry_decision(
        self,
        *,
        decisions: list[dict[str, Any]],
        signal: float | int | str | None,
        side: str,
        allowed: bool,
        reason: str | None,
        price: float,
        timestamp: datetime,
        order_size: float,
    ) -> None:
        """Record whether the current bar generated a valid entry decision."""
        decisions.append(
            {
                "signal": signal,
                "side": side,
                "allowed": allowed,
                "reason": reason,
                "price": price,
                "timestamp": timestamp,
                "order_size": order_size,
            }
        )

    def _create_order(self, *, timestamp: datetime, side: str, size: float) -> PaperOrder:
        self._order_counter += 1
        return PaperOrder(id=f"order-{self._order_counter}", timestamp=timestamp, side=side, size=size)

    def _maybe_route_order(
        self,
        *,
        order: PaperOrder,
        price: float,
        timestamp: datetime,
        cash: float,
        position_size: float,
        avg_entry_price: float | None,
        trades: list[PaperTrade],
    ) -> tuple[float, float, float | None]:
        if self.execution_adapter is None:
            return cash, position_size, avg_entry_price

        report = self.execution_adapter.submit_order(
            order_id=order.id,
            side=order.side,
            size=order.size,
            price=price,
            timestamp=timestamp,
        )
        if report.status not in {"FILLED", "PARTIALLY_FILLED"}:
            order.status = "CANCELED"
            return cash, position_size, avg_entry_price

        fill_size = min(order.size, report.filled_size or order.size)
        execution_price = report.fill_price or price
        cost = report.fee
        if order.side == "buy" and cash >= execution_price * fill_size:
            cash -= execution_price * fill_size
            position_size += fill_size
            avg_entry_price = self._update_average_price(
                current_position=position_size,
                average_price=avg_entry_price,
                fill_size=fill_size,
                fill_price=execution_price,
            )
        elif order.side == "sell" and position_size >= fill_size:
            cash += execution_price * fill_size
            position_size -= fill_size
            if position_size <= 0.0:
                avg_entry_price = None
            else:
                avg_entry_price = avg_entry_price
        else:
            order.status = "CANCELED"
            return cash, position_size, avg_entry_price

        order.filled_size = fill_size
        order.avg_fill_price = execution_price
        order.fees += cost
        order.status = "FILLED"
        order.last_updated_at = timestamp
        trades.append(
            PaperTrade(
                order_id=order.id,
                timestamp=timestamp,
                side=order.side,
                price=execution_price,
                size=fill_size,
                fee=cost,
                cost=cost,
            )
        )
        if self.trade_logger is not None:
            self.trade_logger.log_trade(
                timestamp=timestamp,
                source="paper_trading",
                exchange=self.execution_adapter.name,
                pair="BTC/NOK",
                side=order.side,
                price=execution_price,
                size=fill_size,
                fee=cost,
                role_maker_taker="taker",
                latency_ms=0,
            )
        return cash, position_size, avg_entry_price

    def _evaluate_risk(
        self,
        *,
        bars: Sequence[Any],
        equity: float,
        peak_equity: float,
        current_position: float = 0.0,
        current_bar: Any | None = None,
        bar_index: int | None = None,
        signal_side: str | None = None,
        current_notional: float = 0.0,
        open_positions: int = 0,
        exchange_name: str | None = None,
        exchange_position_size: float = 0.0,
        current_exchange_notional: float = 0.0,
        exchange_open_positions: int = 0,
        open_orders_count: int = 0,
    ) -> Any:
        if self.kill_switch_controller is not None and self.kill_switch_controller.is_active():
            return type("RiskDecision", (), {"allow_entry": False, "position_size": 0.0, "reason": "kill_switch"})()

        if self.risk_manager is None:
            return type("RiskDecision", (), {"allow_entry": True, "position_size": self.default_order_size})()
        return self.risk_manager.evaluate(
            bars=bars,
            equity=equity,
            peak_equity=peak_equity,
            current_position=current_position,
            current_bar=current_bar,
            bar_index=bar_index,
            signal_side=signal_side,
            current_notional=current_notional,
            open_positions=open_positions,
            circuit_breaker=self.circuit_breaker,
            exchange_name=exchange_name or self.exchange_name,
            exchange_position_size=exchange_position_size,
            current_exchange_notional=current_exchange_notional,
            exchange_open_positions=exchange_open_positions,
            open_orders_count=open_orders_count,
        )

    def _apply_cost(self, price: float, *, side: str, size: float) -> float:
        if self.cost_model is None:
            return price
        trade_price = self.cost_model.apply_trade_cost(price, side=side, role="taker", size=size)
        return self.cost_model.apply_fx_cost(trade_price, side=side, size=1.0)

    def _update_average_price(self, *, current_position: float, average_price: float | None, fill_size: float, fill_price: float) -> float | None:
        if current_position <= 0.0:
            return None
        if average_price is None:
            return fill_price
        return ((average_price * (current_position - fill_size)) + (fill_price * fill_size)) / current_position


def _normalize_signal(raw_signal: float | int | str | None) -> float:
    if raw_signal is None:
        return 0.0
    if isinstance(raw_signal, str):
        normalized = raw_signal.strip().lower()
        if normalized in {"buy", "long", "1", "true", "enter"}:
            return 1.0
        if normalized in {"sell", "short", "-1", "false", "exit"}:
            return -1.0
        return 0.0
    return float(raw_signal)


def _get_close(bar: Any) -> float:
    if hasattr(bar, "close"):
        return float(bar.close)
    if isinstance(bar, dict):
        return float(bar["close"])
    raise TypeError("bars must expose a close attribute or be dictionaries with a close key")


def _get_timestamp(bar: Any) -> datetime:
    if hasattr(bar, "timestamp"):
        return bar.timestamp
    if isinstance(bar, dict):
        return bar["timestamp"]
    raise TypeError("bars must expose a timestamp attribute or be dictionaries with a timestamp key")
