"""A lightweight paper-trading engine with a simple order-state machine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Sequence

from src.backtest.costs import CostModel, build_default_cost_model
from src.risk.controls import CircuitBreaker, RiskManager, gate_reentry
from src.risk.kill_switch import KillSwitchController
from src.storage.trade_logger import TradeLogger


@dataclass(slots=True)
class PaperOrder:
    """Simple order model for paper-trading execution."""

    id: str
    timestamp: datetime
    side: str
    size: float
    symbol: str | None = None
    exchange: str | None = None
    status: str = "PENDING_SUBMIT"
    filled_size: float = 0.0
    avg_fill_price: float = 0.0
    fees: float = 0.0
    age_bars: int = 0
    created_at: datetime | None = None
    last_updated_at: datetime | None = None
    last_reason: str | None = None
    execution_status: str | None = None
    execution_message: str | None = None

    def __post_init__(self) -> None:
        self.created_at = self.timestamp
        self.last_updated_at = self.timestamp

    @property
    def remaining_size(self) -> float:
        """Return the remaining order size."""
        return self.size - self.filled_size


@dataclass(slots=True)
class PaperTrade:
    """A simulated fill generated by the paper-trading engine."""

    order_id: str
    timestamp: datetime
    side: str
    price: float
    size: float
    fee: float
    cost: float


@dataclass(slots=True)
class PortfolioSnapshot:
    """Portfolio snapshot after each processing step."""

    timestamp: datetime
    cash: float
    position_size: float
    avg_entry_price: float | None
    equity: float
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    position_side: str = "flat"
    mark_price: float | None = None
    fees_paid: float = 0.0


@dataclass(slots=True)
class PaperTradingResult:
    """Result bundle from a paper-trading run."""

    orders: list[PaperOrder] = field(default_factory=list)
    trades: list[PaperTrade] = field(default_factory=list)
    equity_curve: list[float] = field(default_factory=list)
    portfolio_history: list[PortfolioSnapshot] = field(default_factory=list)
    entry_decisions: list[dict[str, Any]] = field(default_factory=list)


class PaperTradingEngine:
    """Run a simple signal-driven paper-trading loop over OHLC-like bars."""

    def __init__(
        self,
        *,
        initial_cash: float = 100.0,
        default_order_size: float = 1.0,
        partial_fill_fraction: float = 1.0,
        max_order_lifetime_bars: int = 2,
        cost_model: CostModel | None = None,
        risk_manager: RiskManager | None = None,
        trade_logger: TradeLogger | None = None,
        execution_adapter: Any | None = None,
        circuit_breaker: CircuitBreaker | None = None,
        kill_switch_controller: KillSwitchController | None = None,
        exchange_name: str | None = None,
        enable_tax_logging: bool = False,
        strategy_id: str | None = None,
        allow_short: bool = False,
        record_derivative_ledger: bool = False,
    ) -> None:
        """Initialize the object with its runtime state."""
        if initial_cash <= 0:
            raise ValueError("initial_cash must be positive")
        if default_order_size <= 0:
            raise ValueError("default_order_size must be positive")
        if not 0.0 < partial_fill_fraction <= 1.0:
            raise ValueError("partial_fill_fraction must be between 0 and 1")
        if max_order_lifetime_bars < 1:
            raise ValueError("max_order_lifetime_bars must be at least 1")

        self.initial_cash = initial_cash
        self.default_order_size = default_order_size
        self.partial_fill_fraction = partial_fill_fraction
        self.max_order_lifetime_bars = max_order_lifetime_bars
        self.cost_model = cost_model or build_default_cost_model("mock")
        self.risk_manager = risk_manager
        self.trade_logger = trade_logger
        self.execution_adapter = execution_adapter
        self.circuit_breaker = circuit_breaker
        self.kill_switch_controller = kill_switch_controller
        self.exchange_name = exchange_name or getattr(execution_adapter, "exchange_name", None) or getattr(execution_adapter, "name", None) or "paper"
        self.enable_tax_logging = enable_tax_logging
        self.strategy_id = strategy_id
        # Only meaningful for run_exchange_cycle() (live_dry_run/live): whether
        # a flat position may be opened short. Real Kraken spot has no margin
        # support, so this must stay False for --runtime live; it exists so
        # live_dry_run (always sandbox-simulated, never a real order) can
        # exercise short-side behavior for research/testing.
        self.allow_short = allow_short
        # Perpetual futures: book realized PnL, fees and funding from a margin adapter into the tax ledger.
        self.record_derivative_ledger = record_derivative_ledger
        self._derivative_ledger_seen: dict[str, float] | None = None
        # Side ("long"/"short") a risk stop just closed. Re-entering it waits until the strategy's signal has
        # left that side at least once, so a stop can't be undone on the next bar by an unchanged signal.
        self._reentry_block: str | None = None
        self._order_counter = 0
        # Instance-level so the daily-loss reference survives across cycles
        # within one running process (exchange-cycle mode has no other place
        # to keep it, since position/cash state is reconstructed from the
        # adapter each cycle rather than carried in local variables).
        self._exchange_current_day: Any | None = None
        self._exchange_day_start_equity: float | None = None
        # Tracks, per order id, how much of that order's filled_size has
        # already been logged as a trade via exchange reconciliation - a
        # real exchange order fills asynchronously (submit_order returns
        # SUBMITTED, not FILLED), so run_exchange_cycle must poll for fills
        # that happened between cycles rather than assume flat/no-fill.
        # Keyed by order id so a partial fill only logs its new delta.
        self._reconciled_fill_size_by_order_id: dict[str, float] = {}

    def run(self, bars: Sequence[Any], signals: Sequence[float | int | str | None]) -> PaperTradingResult:
        """Process a stream of bars and signals into simulated orders and fills."""
        if len(bars) != len(signals):
            raise ValueError("bars and signals must be the same length")
        if not bars:
            return PaperTradingResult()

        cash = self.initial_cash
        position_size = 0.0
        avg_entry_price: float | None = None
        peak_equity = self.initial_cash
        fees_paid = 0.0
        realized_pnl = 0.0
        orders: list[PaperOrder] = []
        trades: list[PaperTrade] = []
        equity_curve: list[float] = []
        portfolio_history: list[PortfolioSnapshot] = []
        entry_decisions: list[dict[str, Any]] = []
        active_orders: list[PaperOrder] = []
        bars_held = 0
        current_day: Any | None = None
        day_start_equity = self.initial_cash

        reentry_block: str | None = None
        for index, bar in enumerate(bars):
            signal, reentry_block, _blocked = gate_reentry(_normalize_signal(signals[index]), reentry_block)
            price = _get_close(bar)
            timestamp = _get_timestamp(bar)
            current_equity = cash + (position_size * price if position_size else 0.0)

            bar_day = timestamp.date() if hasattr(timestamp, "date") else None
            if bar_day is not None and bar_day != current_day:
                current_day = bar_day
                day_start_equity = current_equity
            bars_held = bars_held + 1 if position_size != 0.0 else 0

            for order in list(active_orders):
                if order.status == "PENDING_SUBMIT":
                    order.status = "OPEN"
                    order.last_updated_at = timestamp
                    continue

                if order.status == "OPEN" and order.remaining_size > 0.0:
                    order.age_bars += 1
                    if order.age_bars >= self.max_order_lifetime_bars:
                        order.status = "CANCELED"
                        order.last_reason = "max_order_lifetime_bars"
                        order.last_updated_at = timestamp
                        active_orders.remove(order)
                        self._log_order_event(
                            order=order,
                            timestamp=timestamp,
                            event_type="order_lifecycle",
                            message="order canceled because it exceeded its lifetime",
                            reason=order.last_reason,
                        )
                        continue

                    fill_size = min(order.remaining_size, self.default_order_size * self.partial_fill_fraction)
                    if fill_size <= 0.0:
                        continue

                    gross_price = price
                    execution_price = self._apply_cost(price, side=order.side, size=fill_size)
                    cost = abs(execution_price - gross_price) * fill_size
                    fees_paid += cost
                    if order.side == "buy" and cash >= execution_price * fill_size:
                        cash -= execution_price * fill_size
                        position_size += fill_size
                        avg_entry_price = self._update_average_price(
                            current_position=position_size,
                            average_price=avg_entry_price,
                            fill_size=fill_size,
                            fill_price=execution_price,
                        )
                    elif order.side == "sell" and position_size >= fill_size:
                        realized_pnl += (execution_price - (avg_entry_price or execution_price)) * fill_size
                        cash += execution_price * fill_size
                        position_size -= fill_size
                        if position_size <= 0.0:
                            avg_entry_price = None
                        else:
                            avg_entry_price = avg_entry_price
                    else:
                        order.status = "CANCELED"
                        order.last_reason = "insufficient_cash_or_position"
                        order.last_updated_at = timestamp
                        active_orders.remove(order)
                        self._log_order_event(
                            order=order,
                            timestamp=timestamp,
                            event_type="order_lifecycle",
                            message="order canceled because cash or inventory was insufficient for the fill",
                            reason=order.last_reason,
                        )
                        continue

                    order.filled_size += fill_size
                    order.avg_fill_price = execution_price
                    order.fees += cost
                    order.last_updated_at = timestamp
                    if order.remaining_size <= 0.0:
                        order.status = "FILLED"
                        active_orders.remove(order)
                        self._log_order_event(
                            order=order,
                            timestamp=timestamp,
                            event_type="order_lifecycle",
                            message="order filled",
                            reason=None,
                            fill_price=execution_price,
                            fill_size=fill_size,
                        )
                    else:
                        order.status = "PARTIALLY_FILLED"
                        self._log_order_event(
                            order=order,
                            timestamp=timestamp,
                            event_type="order_lifecycle",
                            message="order partially filled",
                            reason=None,
                            fill_price=execution_price,
                            fill_size=fill_size,
                        )

                    trades.append(
                        PaperTrade(
                            order_id=order.id,
                            timestamp=timestamp,
                            side=order.side,
                            price=execution_price,
                            size=fill_size,
                            fee=cost,
                            cost=cost,
                        )
                    )
                    if self.trade_logger is not None:
                        self.trade_logger.log_trade(
                            timestamp=timestamp,
                            source="paper_trading",
                            exchange=order.exchange or _get_exchange(bar) or self.exchange_name,
                            pair=order.symbol or _get_symbol(bar) or "unknown",
                            side=order.side,
                            price=execution_price,
                            size=fill_size,
                            fee=cost,
                            role_maker_taker="taker",
                            latency_ms=0,
                            record_tax_event=self.enable_tax_logging,
                            strategy_id=self.strategy_id,
                        )

            forced_exit_reason: str | None = None
            if not active_orders and position_size != 0.0 and self.risk_manager is not None:
                position_side = "long" if position_size > 0.0 else "short"
                exit_decision = self.risk_manager.evaluate_exit(
                    bars=list(bars[: index + 1]),
                    current_bar=bar,
                    position_side=position_side,
                    avg_entry_price=avg_entry_price,
                    bars_held=bars_held,
                )
                if exit_decision.force_exit:
                    forced_exit_reason = exit_decision.reason

            if not active_orders and forced_exit_reason is not None:
                exit_side = "sell" if position_size > 0.0 else "buy"
                reentry_block = "long" if position_size > 0.0 else "short"
                order = self._create_order(timestamp=timestamp, side=exit_side, size=abs(position_size), bar=bar)
                order.last_reason = forced_exit_reason
                active_orders.append(order)
                orders.append(order)
                self._log_order_event(
                    order=order,
                    timestamp=timestamp,
                    event_type="order_lifecycle",
                    message="position force-closed by risk control",
                    reason=forced_exit_reason,
                )
                cash, position_size, avg_entry_price = self._maybe_route_order(
                    order=order,
                    price=price,
                    timestamp=timestamp,
                    cash=cash,
                    position_size=position_size,
                    avg_entry_price=avg_entry_price,
                    trades=trades,
                )
                if order.status in {"FILLED", "CANCELED"}:
                    active_orders.remove(order)
                bars_held = 0
            elif not active_orders:
                if position_size > 0.0 and signal <= 0.0:
                    order = self._create_order(timestamp=timestamp, side="sell", size=position_size, bar=bar)
                    active_orders.append(order)
                    orders.append(order)
                    cash, position_size, avg_entry_price = self._maybe_route_order(
                        order=order,
                        price=price,
                        timestamp=timestamp,
                        cash=cash,
                        position_size=position_size,
                        avg_entry_price=avg_entry_price,
                        trades=trades,
                    )
                    if order.status in {"FILLED", "CANCELED"}:
                        active_orders.remove(order)
                elif position_size < 0.0 and signal >= 0.0:
                    order = self._create_order(timestamp=timestamp, side="buy", size=abs(position_size), bar=bar)
                    active_orders.append(order)
                    orders.append(order)
                    cash, position_size, avg_entry_price = self._maybe_route_order(
                        order=order,
                        price=price,
                        timestamp=timestamp,
                        cash=cash,
                        position_size=position_size,
                        avg_entry_price=avg_entry_price,
                        trades=trades,
                    )
                    if order.status in {"FILLED", "CANCELED"}:
                        active_orders.remove(order)
                elif signal > 0 and position_size <= 0.0:
                    risk_decision = self._evaluate_risk(
                        bars=list(bars[: index + 1]),
                        equity=current_equity,
                        peak_equity=peak_equity,
                        current_position=position_size,
                        current_bar=bar,
                        bar_index=index,
                        signal_side="buy",
                        current_notional=max(0.0, position_size * price),
                        open_positions=1 if position_size != 0.0 else 0,
                        exchange_name=self.exchange_name,
                        exchange_position_size=position_size,
                        current_exchange_notional=max(0.0, position_size * price),
                        exchange_open_positions=1 if position_size != 0.0 else 0,
                        open_orders_count=len(active_orders),
                        daily_reference_equity=day_start_equity,
                    )
                    self._record_entry_decision(
                        decisions=entry_decisions,
                        signal=signal,
                        side="buy",
                        allowed=risk_decision.allow_entry,
                        reason=getattr(risk_decision, "reason", None),
                        price=price,
                        timestamp=timestamp,
                        order_size=risk_decision.position_size,
                        cash=cash,
                        position_size=position_size,
                        equity=current_equity,
                        risk_details=self._build_risk_details(bars=list(bars[: index + 1]), price=price, equity=current_equity, risk_decision=risk_decision),
                    )
                    if risk_decision.allow_entry:
                        order_size = self._resolve_order_size(
                            price=price,
                            cash=cash,
                            equity=current_equity,
                            requested_size=self.default_order_size,
                            risk_position_size=risk_decision.position_size,
                            equity_fraction=getattr(risk_decision, "equity_fraction", None),
                        )
                        if order_size > 0.0:
                            order = self._create_order(timestamp=timestamp, side="buy", size=order_size, bar=bar)
                            active_orders.append(order)
                            orders.append(order)
                            cash, position_size, avg_entry_price = self._maybe_route_order(
                                order=order,
                                price=price,
                                timestamp=timestamp,
                                cash=cash,
                                position_size=position_size,
                                avg_entry_price=avg_entry_price,
                                trades=trades,
                            )
                            if order.status in {"FILLED", "CANCELED"}:
                                active_orders.remove(order)
                elif signal < 0 and position_size >= 0.0:
                    risk_decision = self._evaluate_risk(
                        bars=list(bars[: index + 1]),
                        equity=current_equity,
                        peak_equity=peak_equity,
                        current_position=position_size,
                        current_bar=bar,
                        bar_index=index,
                        signal_side="sell",
                        current_notional=max(0.0, position_size * price),
                        open_positions=1 if position_size != 0.0 else 0,
                        exchange_name=self.exchange_name,
                        exchange_position_size=position_size,
                        current_exchange_notional=max(0.0, position_size * price),
                        exchange_open_positions=1 if position_size != 0.0 else 0,
                        open_orders_count=len(active_orders),
                        daily_reference_equity=day_start_equity,
                    )
                    self._record_entry_decision(
                        decisions=entry_decisions,
                        signal=signal,
                        side="sell",
                        allowed=risk_decision.allow_entry,
                        reason=getattr(risk_decision, "reason", None),
                        price=price,
                        timestamp=timestamp,
                        order_size=risk_decision.position_size,
                        cash=cash,
                        position_size=position_size,
                        equity=current_equity,
                        risk_details=self._build_risk_details(bars=list(bars[: index + 1]), price=price, equity=current_equity, risk_decision=risk_decision),
                    )
                    if risk_decision.allow_entry:
                        order_size = self._resolve_order_size(
                            price=price,
                            cash=cash,
                            equity=current_equity,
                            requested_size=self.default_order_size,
                            risk_position_size=risk_decision.position_size,
                            equity_fraction=getattr(risk_decision, "equity_fraction", None),
                        )
                        if order_size > 0.0:
                            order = self._create_order(timestamp=timestamp, side="sell", size=order_size, bar=bar)
                            active_orders.append(order)
                            orders.append(order)
                            cash, position_size, avg_entry_price = self._maybe_route_order(
                                order=order,
                                price=price,
                                timestamp=timestamp,
                                cash=cash,
                                position_size=position_size,
                                avg_entry_price=avg_entry_price,
                                trades=trades,
                            )
                            if order.status in {"FILLED", "CANCELED"}:
                                active_orders.remove(order)
            equity = cash + (position_size * price if position_size else 0.0)
            peak_equity = max(peak_equity, equity)
            position_side = "flat"
            unrealized_pnl = 0.0
            if position_size > 0.0:
                position_side = "long"
                unrealized_pnl = (position_size * price) - (position_size * (avg_entry_price or 0.0))
            elif position_size < 0.0:
                position_side = "short"
                unrealized_pnl = (position_size * price) - (position_size * (avg_entry_price or 0.0))
            equity_curve.append(equity)
            portfolio_history.append(
                PortfolioSnapshot(
                    timestamp=timestamp,
                    cash=cash,
                    position_size=position_size,
                    avg_entry_price=avg_entry_price,
                    equity=equity,
                    unrealized_pnl=unrealized_pnl,
                    realized_pnl=realized_pnl,
                    position_side=position_side,
                    mark_price=price,
                    fees_paid=fees_paid,
                )
            )
            if self.trade_logger is not None:
                self.trade_logger.log_equity_snapshot(
                    timestamp=timestamp,
                    source="paper_trading",
                    equity=equity,
                    cash=cash,
                    position_size=position_size,
                )

        return PaperTradingResult(
            orders=orders,
            trades=trades,
            equity_curve=equity_curve,
            portfolio_history=portfolio_history,
            entry_decisions=entry_decisions,
        )

    def run_exchange_cycle(self, bars: Sequence[Any], signals: Sequence[float | int | str | None]) -> PaperTradingResult:
        """Process only the latest bar against adapter-backed state for live-style execution."""
        if len(bars) != len(signals):
            raise ValueError("bars and signals must be the same length")
        if not bars:
            return PaperTradingResult()
        if self.execution_adapter is None:
            raise ValueError("exchange-backed cycles require an execution adapter")

        bar = bars[-1]
        raw_signal = _normalize_signal(signals[-1])
        signal, self._reentry_block, reentry_blocked = gate_reentry(raw_signal, self._reentry_block)
        price = _get_close(bar)
        timestamp = _get_timestamp(bar)
        symbol = _get_symbol(bar)
        entry_decisions: list[dict[str, Any]] = []
        trades: list[PaperTrade] = list(self._reconcile_exchange_fills(timestamp=timestamp))
        cycle_orders: list[PaperOrder] = []
        self._capture_derivative_baseline()
        self._apply_market_update(symbol=symbol, price=price, timestamp=timestamp)
        adapter_orders = list(getattr(self.execution_adapter, "list_orders", lambda: [])() or [])
        open_orders = [
            order for order in adapter_orders if getattr(order, "status", None) not in {"FILLED", "CANCELED", "REJECTED", "NOT_FOUND"}
        ]
        cash, position_size, avg_entry_price, fees_paid, position_opened_at = self._current_account_state(price=price, symbol=symbol)
        current_equity = self._account_equity(cash=cash, position_size=position_size, avg_entry_price=avg_entry_price, price=price)

        bar_day = timestamp.date() if hasattr(timestamp, "date") else None
        if bar_day is not None and bar_day != self._exchange_current_day:
            self._exchange_current_day = bar_day
            self._exchange_day_start_equity = current_equity

        forced_exit_reason: str | None = None
        if position_size != 0.0 and self.risk_manager is not None:
            bars_held = 0
            if position_opened_at is not None:
                bars_held = sum(
                    1 for candidate_bar in bars if (candidate_timestamp := _get_timestamp(candidate_bar)) is not None and candidate_timestamp >= position_opened_at
                )
            exit_decision = self.risk_manager.evaluate_exit(
                bars=list(bars),
                current_bar=bar,
                position_side="long" if position_size > 0.0 else "short",
                avg_entry_price=avg_entry_price,
                bars_held=bars_held,
                liquidation_price=self._liquidation_price(),
            )
            if exit_decision.force_exit:
                forced_exit_reason = exit_decision.reason

        if reentry_blocked and position_size == 0.0 and not open_orders:
            self._record_entry_decision(
                decisions=entry_decisions,
                signal=raw_signal,
                side="buy" if raw_signal > 0.0 else "sell",
                allowed=False,
                reason="reentry_after_forced_exit",
                price=price,
                timestamp=timestamp,
                order_size=0.0,
                cash=cash,
                position_size=position_size,
                equity=current_equity,
            )

        if open_orders:
            self._record_entry_decision(
                decisions=entry_decisions,
                signal=signal,
                side="buy" if signal >= 0.0 else "sell",
                allowed=False,
                reason="open_orders_pending",
                price=price,
                timestamp=timestamp,
                order_size=0.0,
                cash=cash,
                position_size=position_size,
                equity=current_equity,
            )
        elif forced_exit_reason is not None:
            exit_side = "sell" if position_size > 0.0 else "buy"
            self._reentry_block = "long" if position_size > 0.0 else "short"
            exit_order = self._create_order(timestamp=timestamp, side=exit_side, size=abs(position_size), bar=bar)
            exit_order.last_reason = forced_exit_reason
            cycle_orders.append(exit_order)
            self._log_order_event(
                order=exit_order,
                timestamp=timestamp,
                event_type="order_lifecycle",
                message="position force-closed by risk control",
                reason=forced_exit_reason,
            )
            maybe_trade = self._route_exchange_order(order=exit_order, price=price, timestamp=timestamp)
            if maybe_trade is not None:
                trades.append(maybe_trade)
        elif position_size > 0.0 and signal <= 0.0:
            exit_order = self._create_order(timestamp=timestamp, side="sell", size=position_size, bar=bar)
            cycle_orders.append(exit_order)
            maybe_trade = self._route_exchange_order(order=exit_order, price=price, timestamp=timestamp)
            if maybe_trade is not None:
                trades.append(maybe_trade)
        elif position_size < 0.0 and signal >= 0.0:
            exit_order = self._create_order(timestamp=timestamp, side="buy", size=abs(position_size), bar=bar)
            cycle_orders.append(exit_order)
            maybe_trade = self._route_exchange_order(order=exit_order, price=price, timestamp=timestamp)
            if maybe_trade is not None:
                trades.append(maybe_trade)
        elif signal > 0.0 and position_size == 0.0:
            risk_decision = self._evaluate_risk(
                bars=list(bars),
                equity=current_equity,
                peak_equity=max(self.initial_cash, current_equity),
                current_position=position_size,
                current_bar=bar,
                bar_index=len(bars) - 1,
                signal_side="buy",
                current_notional=max(0.0, position_size * price),
                open_positions=1 if position_size != 0.0 else 0,
                exchange_name=self.exchange_name,
                exchange_position_size=position_size,
                current_exchange_notional=max(0.0, position_size * price),
                exchange_open_positions=1 if position_size != 0.0 else 0,
                open_orders_count=0,
                daily_reference_equity=self._exchange_day_start_equity,
            )
            self._record_entry_decision(
                decisions=entry_decisions,
                signal=signal,
                side="buy",
                allowed=risk_decision.allow_entry,
                reason=getattr(risk_decision, "reason", None),
                price=price,
                timestamp=timestamp,
                order_size=risk_decision.position_size,
                cash=cash,
                position_size=position_size,
                equity=current_equity,
                risk_details=self._build_risk_details(bars=list(bars), price=price, equity=current_equity, risk_decision=risk_decision),
            )
            if risk_decision.allow_entry:
                order_size = self._resolve_order_size(
                    price=price,
                    cash=self._entry_buying_power(cash=cash, price=price),
                    equity=current_equity,
                    requested_size=self.default_order_size,
                    risk_position_size=risk_decision.position_size,
                    equity_fraction=getattr(risk_decision, "equity_fraction", None),
                )
                if order_size > 0.0:
                    entry_order = self._create_order(timestamp=timestamp, side="buy", size=order_size, bar=bar)
                    cycle_orders.append(entry_order)
                    maybe_trade = self._route_exchange_order(order=entry_order, price=price, timestamp=timestamp)
                    if maybe_trade is not None:
                        trades.append(maybe_trade)
        elif signal < 0.0 and position_size == 0.0 and not self.allow_short:
            self._record_entry_decision(
                decisions=entry_decisions,
                signal=signal,
                side="sell",
                allowed=False,
                reason="spot_shorting_disabled",
                price=price,
                timestamp=timestamp,
                order_size=0.0,
                cash=cash,
                position_size=position_size,
                equity=current_equity,
            )
        elif signal < 0.0 and position_size == 0.0 and self.allow_short:
            risk_decision = self._evaluate_risk(
                bars=list(bars),
                equity=current_equity,
                peak_equity=max(self.initial_cash, current_equity),
                current_position=position_size,
                current_bar=bar,
                bar_index=len(bars) - 1,
                signal_side="sell",
                current_notional=max(0.0, position_size * price),
                open_positions=1 if position_size != 0.0 else 0,
                exchange_name=self.exchange_name,
                exchange_position_size=position_size,
                current_exchange_notional=max(0.0, position_size * price),
                exchange_open_positions=1 if position_size != 0.0 else 0,
                open_orders_count=0,
                daily_reference_equity=self._exchange_day_start_equity,
            )
            self._record_entry_decision(
                decisions=entry_decisions,
                signal=signal,
                side="sell",
                allowed=risk_decision.allow_entry,
                reason=getattr(risk_decision, "reason", None),
                price=price,
                timestamp=timestamp,
                order_size=risk_decision.position_size,
                cash=cash,
                position_size=position_size,
                equity=current_equity,
                risk_details=self._build_risk_details(bars=list(bars), price=price, equity=current_equity, risk_decision=risk_decision),
            )
            if risk_decision.allow_entry:
                order_size = self._resolve_order_size(
                    price=price,
                    cash=self._entry_buying_power(cash=cash, price=price),
                    equity=current_equity,
                    requested_size=self.default_order_size,
                    risk_position_size=risk_decision.position_size,
                    equity_fraction=getattr(risk_decision, "equity_fraction", None),
                )
                if order_size > 0.0:
                    entry_order = self._create_order(timestamp=timestamp, side="sell", size=order_size, bar=bar)
                    cycle_orders.append(entry_order)
                    maybe_trade = self._route_exchange_order(order=entry_order, price=price, timestamp=timestamp)
                    if maybe_trade is not None:
                        trades.append(maybe_trade)

        self._record_derivative_ledger(timestamp=timestamp)
        cash, position_size, avg_entry_price, fees_paid, _position_opened_at = self._current_account_state(price=price, symbol=symbol)
        portfolio_snapshot = self._build_exchange_portfolio_snapshot(
            timestamp=timestamp,
            price=price,
            cash=cash,
            position_size=position_size,
            avg_entry_price=avg_entry_price,
            fees_paid=fees_paid,
        )
        if self.trade_logger is not None:
            self.trade_logger.log_equity_snapshot(
                timestamp=timestamp,
                source="paper_trading",
                equity=portfolio_snapshot.equity,
                cash=portfolio_snapshot.cash,
                position_size=portfolio_snapshot.position_size,
            )

        return PaperTradingResult(
            orders=self._merge_cycle_orders(cycle_orders),
            trades=trades,
            equity_curve=[portfolio_snapshot.equity],
            portfolio_history=[portfolio_snapshot],
            entry_decisions=entry_decisions,
        )

    def run_mark_cycle(self, *, symbol: str | None, price: float, timestamp: datetime) -> PaperTradingResult:
        """Between bar closes: settle pending fills and mark the account to `price`, without trading.

        With a bar interval longer than the poll interval, the strategy only
        acts when a bar completes. The polls in between still pick up fills,
        let a margin account accrue funding and liquidate, and report equity.
        """
        if self.execution_adapter is None:
            raise ValueError("mark cycles require an execution adapter")
        trades = list(self._reconcile_exchange_fills(timestamp=timestamp))
        self._capture_derivative_baseline()
        self._apply_market_update(symbol=symbol, price=price, timestamp=timestamp)
        self._record_derivative_ledger(timestamp=timestamp)
        cash, position_size, avg_entry_price, fees_paid, _opened_at = self._current_account_state(price=price, symbol=symbol)
        snapshot = self._build_exchange_portfolio_snapshot(timestamp=timestamp, price=price, cash=cash, position_size=position_size, avg_entry_price=avg_entry_price, fees_paid=fees_paid)
        return PaperTradingResult(orders=self._merge_cycle_orders([]), trades=trades, equity_curve=[snapshot.equity], portfolio_history=[snapshot], entry_decisions=[])

    def _record_entry_decision(
        self,
        *,
        decisions: list[dict[str, Any]],
        signal: float | int | str | None,
        side: str,
        allowed: bool,
        reason: str | None,
        price: float,
        timestamp: datetime,
        order_size: float,
        cash: float | None = None,
        position_size: float | None = None,
        equity: float | None = None,
        risk_details: dict[str, Any] | None = None,
    ) -> None:
        """Record whether the current bar generated a valid entry decision."""
        decision = {
            "signal": signal,
            "side": side,
            "allowed": allowed,
            "reason": reason,
            "price": price,
            "timestamp": timestamp,
            "order_size": order_size,
        }
        if risk_details:
            decision.update(risk_details)
        decisions.append(decision)
        if self.trade_logger is None:
            return
        self.trade_logger.log_event(
            timestamp=timestamp,
            level="WARNING" if not allowed else "INFO",
            event_type="entry_decision",
            message="entry decision evaluated",
            source="paper_trading",
            metadata={
                "signal": signal,
                "side": side,
                "allowed": allowed,
                "reason": reason,
                "price": price,
                "order_size": order_size,
                "cash": cash,
                "position_size": position_size,
                "equity": equity,
                **(risk_details or {}),
            },
        )

    def _build_risk_details(
        self,
        *,
        bars: list[Any],
        price: float,
        equity: float,
        risk_decision: Any,
    ) -> dict[str, Any]:
        details = {
            "price": price,
            "equity": equity,
        }
        risk_manager = getattr(self, "risk_manager", None)
        if risk_manager is None:
            return details

        volatility_pct = None
        max_volatility_pct = None
        if hasattr(risk_manager, "estimate_volatility"):
            try:
                volatility_pct = risk_manager.estimate_volatility(bars)
            except TypeError:
                volatility_pct = None
        if hasattr(risk_manager, "max_volatility_pct"):
            max_volatility_pct = risk_manager.max_volatility_pct
        elif hasattr(risk_manager, "config") and hasattr(risk_manager.config, "max_volatility_pct"):
            max_volatility_pct = risk_manager.config.max_volatility_pct

        if volatility_pct is not None:
            details["volatility_pct"] = volatility_pct
        if max_volatility_pct is not None:
            details["max_volatility_pct"] = max_volatility_pct
        if hasattr(risk_decision, "position_size"):
            details["risk_position_size"] = risk_decision.position_size
        if hasattr(risk_decision, "reason"):
            details["risk_reason"] = risk_decision.reason
        if getattr(risk_decision, "annual_volatility_forecast", None) is not None:
            details["annual_volatility_forecast"] = risk_decision.annual_volatility_forecast
            details["equity_fraction"] = risk_decision.equity_fraction
        return details

    def _log_order_event(self, *, order: PaperOrder, timestamp: datetime, event_type: str, message: str, reason: str | None = None, **metadata: Any) -> None:
        if self.trade_logger is None:
            return
        payload = {
            "order_id": order.id,
            "side": order.side,
            "status": order.status,
            "execution_status": order.execution_status,
            "execution_message": order.execution_message,
            "size": order.size,
            "filled_size": order.filled_size,
            "remaining_size": order.remaining_size,
            "reason": reason,
            **metadata,
        }
        self.trade_logger.log_event(
            timestamp=timestamp,
            level="WARNING" if reason else "INFO",
            event_type=event_type,
            message=message,
            source="paper_trading",
            metadata=payload,
        )

    def _create_order(self, *, timestamp: datetime, side: str, size: float, bar: Any | None = None) -> PaperOrder:
        self._order_counter += 1
        return PaperOrder(
            id=f"order-{self._order_counter}",
            timestamp=timestamp,
            side=side,
            size=size,
            symbol=_get_symbol(bar),
            exchange=_get_exchange(bar) or self.exchange_name,
        )

    def _maybe_route_order(
        self,
        *,
        order: PaperOrder,
        price: float,
        timestamp: datetime,
        cash: float,
        position_size: float,
        avg_entry_price: float | None,
        trades: list[PaperTrade],
    ) -> tuple[float, float, float | None]:
        if self.execution_adapter is None:
            return cash, position_size, avg_entry_price

        report = self.execution_adapter.submit_order(
            order_id=order.id,
            side=order.side,
            size=order.size,
            price=price,
            timestamp=timestamp,
            symbol=order.symbol,
        )
        order.execution_status = report.status
        order.execution_message = report.message
        if report.status not in {"FILLED", "PARTIALLY_FILLED"}:
            order.status = "CANCELED"
            order.last_reason = report.message or "execution_adapter_rejected_order"
            self._log_order_event(
                order=order,
                timestamp=timestamp,
                event_type="order_lifecycle",
                message="order canceled before fill",
                reason=order.last_reason,
            )
            return cash, position_size, avg_entry_price

        fill_size = min(order.size, report.filled_size or order.size)
        execution_price = report.fill_price or price
        cost = report.fee
        if order.side == "buy" and cash >= execution_price * fill_size:
            cash -= execution_price * fill_size
            position_size += fill_size
            avg_entry_price = self._update_average_price(
                current_position=position_size,
                average_price=avg_entry_price,
                fill_size=fill_size,
                fill_price=execution_price,
            )
        elif order.side == "sell" and position_size >= fill_size:
            cash += execution_price * fill_size
            position_size -= fill_size
            if position_size <= 0.0:
                avg_entry_price = None
            else:
                avg_entry_price = avg_entry_price
        else:
            order.status = "CANCELED"
            order.last_reason = "insufficient_cash_or_position"
            self._log_order_event(
                order=order,
                timestamp=timestamp,
                event_type="order_lifecycle",
                message="order canceled because cash or inventory was insufficient for the fill",
                reason=order.last_reason,
            )
            return cash, position_size, avg_entry_price

        order.filled_size = fill_size
        order.avg_fill_price = execution_price
        order.fees += cost
        order.status = "FILLED"
        order.last_updated_at = timestamp
        self._log_order_event(
            order=order,
            timestamp=timestamp,
            event_type="order_lifecycle",
            message="order filled via execution adapter",
            fill_price=execution_price,
            fill_size=fill_size,
            fee=cost,
        )
        trades.append(
            PaperTrade(
                order_id=order.id,
                timestamp=timestamp,
                side=order.side,
                price=execution_price,
                size=fill_size,
                fee=cost,
                cost=cost,
            )
        )
        if self.trade_logger is not None:
            self.trade_logger.log_trade(
                timestamp=timestamp,
                source="paper_trading",
                exchange=order.exchange or getattr(self.execution_adapter, "exchange_name", None) or self.execution_adapter.name,
                pair=order.symbol or "unknown",
                side=order.side,
                price=execution_price,
                size=fill_size,
                fee=cost,
                role_maker_taker="taker",
                latency_ms=0,
                record_tax_event=self.enable_tax_logging,
                strategy_id=self.strategy_id,
            )
        return cash, position_size, avg_entry_price

    def _route_exchange_order(self, *, order: PaperOrder, price: float, timestamp: datetime) -> PaperTrade | None:
        report = self.execution_adapter.submit_order(
            order_id=order.id,
            side=order.side,
            size=order.size,
            price=price,
            timestamp=timestamp,
            symbol=order.symbol,
        )
        order.execution_status = report.status
        order.execution_message = report.message
        order.last_updated_at = timestamp

        if report.status in {"SUBMITTED", "OPEN"}:
            order.status = report.status
            self._log_order_event(
                order=order,
                timestamp=timestamp,
                event_type="order_lifecycle",
                message="order submitted to execution adapter",
                reason=None,
            )
            return None

        if report.status not in {"FILLED", "PARTIALLY_FILLED"}:
            order.status = "CANCELED"
            order.last_reason = report.message or "execution_adapter_rejected_order"
            self._log_order_event(
                order=order,
                timestamp=timestamp,
                event_type="order_lifecycle",
                message="order canceled before fill",
                reason=order.last_reason,
            )
            return None

        fill_size = min(order.size, report.filled_size or order.size)
        execution_price = report.fill_price or price
        cost = report.fee
        order.filled_size = fill_size
        order.avg_fill_price = execution_price
        order.fees += cost
        order.status = report.status
        self._log_order_event(
            order=order,
            timestamp=timestamp,
            event_type="order_lifecycle",
            message="order filled via execution adapter",
            fill_price=execution_price,
            fill_size=fill_size,
            fee=cost,
        )
        if self.trade_logger is not None:
            self.trade_logger.log_trade(
                timestamp=timestamp,
                source="paper_trading",
                exchange=order.exchange or getattr(self.execution_adapter, "exchange_name", None) or self.execution_adapter.name,
                pair=order.symbol or "unknown",
                side=order.side,
                price=execution_price,
                size=fill_size,
                fee=cost,
                role_maker_taker="taker",
                latency_ms=0,
                record_tax_event=self.enable_tax_logging,
                strategy_id=self.strategy_id,
            )
        return PaperTrade(
            order_id=order.id,
            timestamp=timestamp,
            side=order.side,
            price=execution_price,
            size=fill_size,
            fee=cost,
            cost=cost,
        )

    def _reconcile_exchange_fills(self, *, timestamp: datetime) -> list[PaperTrade]:
        """Poll the exchange adapter for real fills on previously-submitted orders and log any newly-observed fill.

        A real exchange order submitted via submit_order() returns SUBMITTED,
        not FILLED - the fill happens asynchronously on the exchange. Without
        this, the adapter's local balances/positions and the trade log both
        stay stale after a real fill, which lets the next cycle re-enter a
        position it already holds. Short-circuits (no adapter call at all)
        once nothing is pending, so a steady-state flat/no-open-orders cycle
        does not keep polling the exchange for no reason.
        """
        if self.execution_adapter is None:
            return []
        list_orders = getattr(self.execution_adapter, "list_orders", None)
        recover = getattr(self.execution_adapter, "recover_execution_state", None)
        if not callable(list_orders) or not callable(recover):
            return []

        pending_orders = [order for order in list_orders() if getattr(order, "status", None) not in {"FILLED", "CANCELED", "REJECTED", "NOT_FOUND"}]
        if not pending_orders:
            return []

        try:
            recover()
        except Exception as exc:
            if self.trade_logger is not None:
                self.trade_logger.log_event(
                    timestamp=timestamp,
                    level="ERROR",
                    event_type="exchange_reconciliation_error",
                    message="failed to reconcile exchange order state against real fills",
                    source="paper_trading",
                    metadata={"error": str(exc)},
                )
            return []

        new_trades: list[PaperTrade] = []
        for order in list_orders():
            if getattr(order, "status", None) not in {"FILLED", "PARTIALLY_FILLED"}:
                continue
            total_filled = float(getattr(order, "filled_size", 0.0) or 0.0)
            already_logged = self._reconciled_fill_size_by_order_id.get(order.order_id, 0.0)
            new_fill_size = total_filled - already_logged
            if new_fill_size <= 0.0:
                continue
            self._reconciled_fill_size_by_order_id[order.order_id] = total_filled

            fill_price = float(getattr(order, "fill_price", None) or 0.0)
            fee = float(getattr(order, "fee", 0.0) or 0.0)
            new_trades.append(
                PaperTrade(
                    order_id=order.order_id,
                    timestamp=timestamp,
                    side=order.side,
                    price=fill_price,
                    size=new_fill_size,
                    fee=fee,
                    cost=fee,
                )
            )
            if self.trade_logger is not None:
                self.trade_logger.log_trade(
                    timestamp=timestamp,
                    source="paper_trading",
                    exchange=getattr(order, "exchange", None) or self.exchange_name,
                    pair=getattr(order, "symbol", None) or "unknown",
                    side=order.side,
                    price=fill_price,
                    size=new_fill_size,
                    fee=fee,
                    role_maker_taker="taker",
                    latency_ms=0,
                    record_tax_event=self.enable_tax_logging,
                    strategy_id=self.strategy_id,
                )
        return new_trades

    def _derivative_totals(self) -> dict[str, float]:
        adapter = self.execution_adapter
        return {
            "REALIZED_PNL": float(getattr(adapter, "realized_pnl_total", 0.0)),
            "TRADING_FEE": float(getattr(adapter, "fees_paid_total", 0.0)),
            "FUNDING_FEE": float(getattr(adapter, "funding_paid_total", 0.0)),
        }

    def _capture_derivative_baseline(self) -> None:
        # The first cycle only sets the baseline, so totals restored from a saved sandbox state are not booked twice.
        if self.record_derivative_ledger and self._is_margin_account() and self._derivative_ledger_seen is None:
            self._derivative_ledger_seen = self._derivative_totals()

    def _record_derivative_ledger(self, *, timestamp: datetime) -> None:
        """Book realized PnL, fees and funding that the margin account accrued this cycle into the tax ledger."""
        if not self.record_derivative_ledger or self.trade_logger is None or self._derivative_ledger_seen is None:
            return
        contract = getattr(self.execution_adapter, "contract", None)
        venue_symbol = getattr(contract, "venue_symbol", None) or "perpetual"
        currency = getattr(contract, "collateral_currency", None) or "USD"
        current = self._derivative_totals()
        for kind, total in current.items():
            delta = total - self._derivative_ledger_seen[kind]
            if abs(delta) < 1e-9:
                continue
            # Fees and funding totals count money paid out; the ledger stores cash flows (paid = negative).
            amount = delta if kind == "REALIZED_PNL" else -delta
            try:
                self.trade_logger.log_derivative_event(timestamp=timestamp, venue_symbol=venue_symbol, transaction_type=kind, amount=amount, currency=currency, source=self.strategy_id or "runtime")
            except Exception as exc:
                self.trade_logger.log_event(
                    timestamp=timestamp,
                    level="ERROR",
                    event_type="derivative_tax_event_failed",
                    message="could not record a perpetual-futures cash flow in the tax ledger",
                    source="paper_trading",
                    metadata={"kind": kind, "amount": amount, "error": str(exc)},
                )
                continue
            self._derivative_ledger_seen[kind] = total

    def _is_margin_account(self) -> bool:
        return bool(getattr(self.execution_adapter, "margin_account", False))

    def _account_equity(self, *, cash: float, position_size: float, avg_entry_price: float | None, price: float) -> float:
        """Equity for the current account type.

        Spot: cash plus the position valued at `price` (a short is a
        negative holding whose sale proceeds are already in cash). Margin
        account: the wallet already holds only realized results, so equity
        is wallet plus the position's unrealized PnL against its entry.
        """
        if not position_size:
            return cash
        if self._is_margin_account():
            entry = avg_entry_price if avg_entry_price is not None else price
            return cash + position_size * (price - entry)
        return cash + position_size * price

    def _entry_buying_power(self, *, cash: float, price: float) -> float:
        """Cash-like amount used to cap a new entry: cash for spot, free margin times leverage for a margin account."""
        buying_power = getattr(self.execution_adapter, "buying_power", None)
        if self._is_margin_account() and callable(buying_power):
            return float(buying_power(price))
        return cash

    def _liquidation_price(self) -> float | None:
        getter = getattr(self.execution_adapter, "liquidation_price", None)
        return getter() if self._is_margin_account() and callable(getter) else None

    def _apply_market_update(self, *, symbol: str | None, price: float, timestamp: datetime) -> None:
        """Let a margin adapter mark to market, accrue funding and liquidate, and log what it reports."""
        on_market_update = getattr(self.execution_adapter, "on_market_update", None)
        if not callable(on_market_update):
            return
        for event in on_market_update(symbol=symbol, mark_price=price, timestamp=timestamp):
            if self.trade_logger is None:
                continue
            kind = str(event.get("type", "update"))
            event_type, level, message = {
                "liquidation": ("position_liquidated", "ERROR", "position liquidated by the margin account"),
                "funding": ("funding_accrued", "INFO", "funding charged on the open position"),
                "external_position_change": ("position_changed_externally", "WARNING", "exchange position changed without an order from this runtime"),
            }.get(kind, (f"margin_account_{kind}", "INFO", f"margin account reported {kind}"))
            self.trade_logger.log_event(
                timestamp=timestamp,
                level=level,
                event_type=event_type,
                message=message,
                source="paper_trading",
                metadata={key: value for key, value in event.items() if key != "type"},
            )

    def _current_account_state(self, *, price: float, symbol: str | None) -> tuple[float, float, float | None, float, datetime | None]:
        account_snapshot = getattr(self.execution_adapter, "get_account_snapshot", lambda: {})() or {}
        balances = account_snapshot.get("balances", {}) or {}
        positions = account_snapshot.get("positions", {}) or {}
        entry_prices = account_snapshot.get("position_entry_price", {}) or {}
        opened_at_map = account_snapshot.get("position_opened_at", {}) or {}
        base_currency = getattr(self.execution_adapter, "_base_currency", None) or _get_quote_asset(symbol) or "USD"
        position_symbol = _get_position_asset(symbol)
        cash = float(balances.get(base_currency, 0.0))
        position_size = float(positions.get(position_symbol, 0.0)) if position_symbol is not None else 0.0
        position_opened_at: datetime | None = None
        if position_size != 0.0 and position_symbol is not None:
            # Fall back to the current price/None when the adapter doesn't track
            # real entry state (e.g. a test stub), rather than fabricating a
            # value that would silently defeat the ATR-stop/time-stop checks.
            avg_entry_price = entry_prices.get(position_symbol, price)
            position_opened_at = opened_at_map.get(position_symbol)
        else:
            avg_entry_price = None
        fees_paid = 0.0
        adapter_orders = list(getattr(self.execution_adapter, "list_orders", lambda: [])() or [])
        for existing_order in adapter_orders:
            fees_paid += float(getattr(existing_order, "fee", 0.0) or 0.0)
        return cash, position_size, avg_entry_price, fees_paid, position_opened_at

    def _build_exchange_portfolio_snapshot(
        self,
        *,
        timestamp: datetime,
        price: float,
        cash: float,
        position_size: float,
        avg_entry_price: float | None,
        fees_paid: float,
    ) -> PortfolioSnapshot:
        equity = self._account_equity(cash=cash, position_size=position_size, avg_entry_price=avg_entry_price, price=price)
        unrealized_pnl = 0.0
        position_side = "flat"
        if position_size != 0.0:
            position_side = "long" if position_size > 0.0 else "short"
            if avg_entry_price is not None:
                unrealized_pnl = position_size * (price - avg_entry_price)
        return PortfolioSnapshot(
            timestamp=timestamp,
            cash=cash,
            position_size=position_size,
            avg_entry_price=avg_entry_price,
            equity=equity,
            unrealized_pnl=unrealized_pnl,
            realized_pnl=0.0,
            position_side=position_side,
            mark_price=price,
            fees_paid=fees_paid,
        )

    def _snapshot_adapter_orders(self) -> list[PaperOrder]:
        snapshot_orders: list[PaperOrder] = []
        for adapter_order in list(getattr(self.execution_adapter, "list_orders", lambda: [])() or []):
            timestamp = getattr(adapter_order, "timestamp", None) or datetime.now()
            snapshot_orders.append(
                PaperOrder(
                    id=str(getattr(adapter_order, "order_id", "unknown")),
                    timestamp=timestamp,
                    side=str(getattr(adapter_order, "side", "unknown")),
                    size=float(getattr(adapter_order, "size", 0.0) or 0.0),
                    symbol=getattr(adapter_order, "symbol", None),
                    exchange=getattr(adapter_order, "exchange", self.exchange_name),
                    status=str(getattr(adapter_order, "status", "UNKNOWN")),
                    filled_size=float(getattr(adapter_order, "filled_size", 0.0) or 0.0),
                    avg_fill_price=float(getattr(adapter_order, "fill_price", 0.0) or 0.0),
                    fees=float(getattr(adapter_order, "fee", 0.0) or 0.0),
                    last_reason=getattr(adapter_order, "last_reason", None),
                    execution_status=getattr(adapter_order, "remote_status", None) or getattr(adapter_order, "status", None),
                    execution_message=getattr(adapter_order, "message", None),
                )
            )
        return snapshot_orders

    def _merge_cycle_orders(self, cycle_orders: Sequence[PaperOrder]) -> list[PaperOrder]:
        merged: dict[str, PaperOrder] = {order.id: order for order in cycle_orders}
        for snapshot_order in self._snapshot_adapter_orders():
            merged[snapshot_order.id] = snapshot_order
        return list(merged.values())

    def _evaluate_risk(
        self,
        *,
        bars: Sequence[Any],
        equity: float,
        peak_equity: float,
        current_position: float = 0.0,
        current_bar: Any | None = None,
        bar_index: int | None = None,
        signal_side: str | None = None,
        current_notional: float = 0.0,
        open_positions: int = 0,
        exchange_name: str | None = None,
        exchange_position_size: float = 0.0,
        current_exchange_notional: float = 0.0,
        exchange_open_positions: int = 0,
        open_orders_count: int = 0,
        daily_reference_equity: float | None = None,
    ) -> Any:
        if self.kill_switch_controller is not None and self.kill_switch_controller.is_active():
            return type("RiskDecision", (), {"allow_entry": False, "position_size": 0.0, "reason": "kill_switch"})()

        if self.risk_manager is None:
            return type("RiskDecision", (), {"allow_entry": True, "position_size": self.default_order_size})()
        return self.risk_manager.evaluate(
            bars=bars,
            equity=equity,
            peak_equity=peak_equity,
            current_position=current_position,
            current_bar=current_bar,
            bar_index=bar_index,
            signal_side=signal_side,
            current_notional=current_notional,
            open_positions=open_positions,
            circuit_breaker=self.circuit_breaker,
            exchange_name=exchange_name or self.exchange_name,
            exchange_position_size=exchange_position_size,
            current_exchange_notional=current_exchange_notional,
            exchange_open_positions=exchange_open_positions,
            open_orders_count=open_orders_count,
            daily_reference_equity=daily_reference_equity,
        )

    def _resolve_order_size(
        self,
        *,
        price: float,
        cash: float,
        equity: float,
        requested_size: float,
        risk_position_size: float,
        equity_fraction: float | None = None,
    ) -> float:
        if price <= 0.0:
            return 0.0
        max_affordable_size = cash / price
        if max_affordable_size <= 0.0:
            return 0.0
        if equity_fraction is not None:
            # Volatility-target sizing gives a share of equity; it replaces the unit-based caps below.
            return max(0.0, min(equity_fraction * equity / price, max_affordable_size))

        max_risk_fraction = 0.0
        if self.risk_manager is not None and getattr(self.risk_manager, "config", None) is not None:
            max_risk_fraction = float(getattr(self.risk_manager.config, "risk_per_trade_pct", 0.0))

        max_risk_size = float("inf")
        if max_risk_fraction > 0.0:
            max_risk_size = (equity * max_risk_fraction) / price

        return max(0.0, min(requested_size, risk_position_size, max_affordable_size, max_risk_size))

    def _apply_cost(self, price: float, *, side: str, size: float) -> float:
        if self.cost_model is None:
            return price
        trade_price = self.cost_model.apply_trade_cost(price, side=side, role="taker", size=size)
        return self.cost_model.apply_fx_cost(trade_price, side=side, size=1.0)

    def _update_average_price(self, *, current_position: float, average_price: float | None, fill_size: float, fill_price: float) -> float | None:
        if current_position <= 0.0:
            return None
        if average_price is None:
            return fill_price
        return ((average_price * (current_position - fill_size)) + (fill_price * fill_size)) / current_position


def _normalize_signal(raw_signal: float | int | str | None) -> float:
    if raw_signal is None:
        return 0.0
    if isinstance(raw_signal, str):
        normalized = raw_signal.strip().lower()
        if normalized in {"buy", "long", "1", "true", "enter"}:
            return 1.0
        if normalized in {"sell", "short", "-1", "false", "exit"}:
            return -1.0
        return 0.0
    return float(raw_signal)


def _get_close(bar: Any) -> float:
    if hasattr(bar, "close"):
        return float(bar.close)
    if isinstance(bar, dict):
        return float(bar["close"])
    raise TypeError("bars must expose a close attribute or be dictionaries with a close key")


def _get_symbol(bar: Any) -> str | None:
    if bar is None:
        return None
    if hasattr(bar, "symbol"):
        value = getattr(bar, "symbol")
        return str(value) if value is not None else None
    if isinstance(bar, dict):
        value = bar.get("symbol")
        return str(value) if value is not None else None
    return None


def _get_exchange(bar: Any) -> str | None:
    if bar is None:
        return None
    if hasattr(bar, "exchange"):
        value = getattr(bar, "exchange")
        return str(value) if value is not None else None
    if isinstance(bar, dict):
        value = bar.get("exchange")
        return str(value) if value is not None else None
    return None


def _get_position_asset(symbol: str | None) -> str | None:
    normalized = str(symbol or "").strip().upper()
    for separator in ("/", "-", "_", ":"):
        if separator in normalized:
            base_asset = normalized.split(separator, 1)[0].strip()
            return base_asset or None
    return normalized or None


def _get_quote_asset(symbol: str | None) -> str | None:
    normalized = str(symbol or "").strip().upper()
    for separator in ("/", "-", "_", ":"):
        if separator in normalized:
            quote_asset = normalized.split(separator, 1)[1].strip()
            return quote_asset or None
    return None


def _get_timestamp(bar: Any) -> datetime:
    if hasattr(bar, "timestamp"):
        return bar.timestamp
    if isinstance(bar, dict):
        return bar["timestamp"]
    raise TypeError("bars must expose a timestamp attribute or be dictionaries with a timestamp key")
