"""A lightweight event-driven simulator for simple paper-trading execution."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Sequence

from src.storage.order_book import OrderBookSnapshot


@dataclass(slots=True)
class EventDrivenTrade:
    """A single trade generated by the simulator."""

    timestamp: datetime
    side: str
    price: float
    size: float
    latency_ms: int


@dataclass(slots=True)
class EventDrivenSimulator:
    """Execute a simple signal stream against a sequence of order book snapshots."""

    latency_ms: int = 100
    max_slippage: float = 0.01
    initial_equity: float = 100.0
    position_size: float = 1.0

    def __init__(
        self,
        latency_ms: int = 100,
        max_slippage: float = 0.01,
        initial_equity: float = 100.0,
        position_size: float = 1.0,
    ) -> None:
        self.latency_ms = latency_ms
        self.max_slippage = max_slippage
        self.initial_equity = initial_equity
        self.position_size = position_size

    def run(self, snapshots: Sequence[OrderBookSnapshot], signals: Sequence[float]) -> tuple[list[EventDrivenTrade], list[float]]:
        """Simulate fills over a stream of snapshots and signals."""
        if len(snapshots) != len(signals):
            raise ValueError("snapshots and signals must be the same length")
        if not snapshots:
            return [], []

        equity = self.initial_equity
        trades: list[EventDrivenTrade] = []
        equity_curve: list[float] = [equity]
        position = 0.0
        entry_price: float | None = None
        entry_timestamp: datetime | None = None

        for index, snapshot in enumerate(snapshots):
            signal = signals[index]
            if snapshot.timestamp is None:
                snapshot.timestamp = datetime.now()

            if signal > 0 and position <= 0:
                price = self._fill_price(snapshot, side="buy")
                position = self.position_size
                entry_price = price
                entry_timestamp = snapshot.timestamp
            elif signal < 0 and position >= 0:
                price = self._fill_price(snapshot, side="sell")
                position = -self.position_size
                entry_price = price
                entry_timestamp = snapshot.timestamp
            elif position != 0 and signal == 0:
                if entry_price is None or entry_timestamp is None:
                    continue
                exit_price = self._fill_price(snapshot, side="sell" if position > 0 else "buy")
                pnl = (exit_price - entry_price) / entry_price if position > 0 else (entry_price - exit_price) / entry_price
                equity *= 1 + pnl
                trades.append(
                    EventDrivenTrade(
                        timestamp=snapshot.timestamp,
                        side="long" if position > 0 else "short",
                        price=exit_price,
                        size=self.position_size,
                        latency_ms=self.latency_ms,
                    )
                )
                position = 0.0
                entry_price = None
                entry_timestamp = None
            equity_curve.append(equity)

        return trades, equity_curve

    def _fill_price(self, snapshot: OrderBookSnapshot, *, side: str) -> float:
        if side == "buy":
            best_ask = snapshot.asks[0][0] if snapshot.asks else 0.0
            return best_ask * (1 + self.max_slippage)
        if side == "sell":
            best_bid = snapshot.bids[0][0] if snapshot.bids else 0.0
            return best_bid * (1 - self.max_slippage)
        raise ValueError("side must be buy or sell")
